# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32c8b42cfac7192dbf1298142fcbdb010afe92625b64eed00556a006112516faaf1bae6c8d2aee7c9fe309e77fb1cb1e6f5b434892289cfecc6e63da90d31c07

test:
  secret_key_base: b873b1c8a42be154a03cffd6215efd0534bceff989a8d96db65312109505503edf5142067c2004e961e9cf7822b33549ab22a227d78a8eecba13abaa9816d84e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
